olymp/api/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('api.views',
                       # Examples:
                       # url(r'^$', 'tosterproject.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       url(r'^get_schools/', 'get_schools', name='get_schools'),
                       url(r'^$', 'home', name='home'),
                       url(r'^get_districts/', 'get_districts', name='get_districts'),
                       url(r'^csv/', 'upload_data', name='upload-data')

                       )

olymp/check_app/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('check_app.views',
                       # Examples:
                       # url(r'^$', 'tosterproject.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),
                       url(r"^$", 'index', name='home'),
                       url(r"^process/(?P<id>[0-9]+)/$", 'user_check', name='process'),
                       url(r"^results/$", 'results', name='results'),
                       url(r'^list/$', 'list', name='list'),
                       url(r'^pdf/(?P<uid>[0-9]+)/$', 'get_pdf', name='pdf'),
                       url(r'^stats/$', 'stats', name='stats'),
                       url(r'^will/$', 'get_list_of_participants', name='parts'),
                       url(r'^gen/(?P<uid>[0-9]+)/$', 'gen_pdf', name='gen'),
                       url(r'^gen2/(?P<uid>[0-9]+)/$', 'gen_pdf_onsite', name='gen2'),
                       url(r'^pdf2/(?P<uid>[0-9]+)/$', 'get_pdf_nosite', name='pdf2'),
                       url(r'^questions/(?P<subject_id>[0-9]+)$', 'questions_list',
                           name='questions'),
                       url(r'^questions/', 'questions_list', name='questions_list'),
                       url(r'^partstats/', 'statistics_participants', name='partstats')
                       # url(r'^login/$', LoginView.as_view(), name='login'),
                       # url(r'^logout/$', 'log_out', name='logout'),
                       # url(r'^class/(?P<class_id>\d+)/$', 'class_journal', name='class_journal'),
                       # url(r'^test/$', 'raiting2', name='raiting2'),
                       # url(r'^class/(?P<class_id>\d+)/master$', 'class_journal', name='my_class'),
                       # url(r'^student/(?P<student_id>\d+)/$', 'student_profile', name='student'),
                       # url(r'^raiting/$', 'raiting', name='raiting'),
                       # url(r'^inc/$', 'increase', name='inc')
                       # url(r'^event/(?P<event_id>\d+)/edit/$', 'event_edit', name='event_edit')
                       )

olymp/olymp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import password_reset
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from olymp import settings
from userman.views import LoginView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', LoginView.as_view(), name='loginn'),
    url(r'^$', 'userman.views.index', name='main'),
    url(r'^register/', 'userman.views.register', name='register'),
    url(r'^logout/', 'userman.views.log_out', name='logoutt'),
    url(r'^accounts/registration/$',
        password_reset,
        {'html_email_template_name':
             'registration/password_reset_email_html.html', },
        name='registration',
        ),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^data/upload/', 'userman.data_manager.backup.upload', name='upload'),
    url(r"^api/", include('api.urls'), name="api"),
    url(r'^confirm/(?P<activation_key>\w+)/', 'userman.views.register_confirm', name='register_confirm'),
    url(r'^register_success/', 'userman.views.register_success', name='register_success'),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^contact/', 'userman.views.contact', name='contact'),
    url(r'^test/', include('test_app.urls', namespace='test-app')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}
        ),
    url(r'^check/', include('check_app.urls', namespace='check')),
    url(r'^program/', 'userman.views.program', name='program'),

]

urlpatterns += staticfiles_urlpatterns()

olymp/test_app/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('test_app.views',
                       # Examples:
                       # url(r'^$', 'tosterproject.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       url(r"^$", 'home', name='home'),
                       url(r"^process/(?P<question_number>[0-9]+)/", 'process', name='process'),
                       url(r"^process/$", 'process', name='process'),
                       url(r"^update/", 'update_db', name='update_db'),
                       url(r'^finished/', 'finished', name='finished'),
                       url(r'^finally-finished/', 'finally_finished', name='finally-finished'),
                       url(r'^timeout/', 'timeout', name='timeout'),
                       url(r'^html/', 'test_html', name='test_html'),
                       url(r'^res/', 'results', name='res'),
                       url(r'^final/','final_results', name='final'),
                       url(r'^confirm/', 'confirm_part', name='confirm'),
                       url(r'^confirm_1st/', 'confirm_1st', name='confirm_1st'),
                       url(r'^not_started/', 'olymp_not_started', name='not_started')


                       # url(r'^login/$', LoginView.as_view(), name='login'),
                       # url(r'^logout/$', 'log_out', name='logout'),
                       # url(r'^class/(?P<class_id>\d+)/$', 'class_journal', name='class_journal'),
                       # url(r'^test/$', 'raiting2', name='raiting2'),
                       # url(r'^class/(?P<class_id>\d+)/master$', 'class_journal', name='my_class'),
                       # url(r'^student/(?P<student_id>\d+)/$', 'student_profile', name='student'),
                       # url(r'^raiting/$', 'raiting', name='raiting'),
                       # url(r'^inc/$', 'increase', name='inc')
                       # url(r'^event/(?P<event_id>\d+)/edit/$', 'event_edit', name='event_edit')
                       )

olymp/test_app/views.py
from datetime import timedelta, datetime
from time import mktime
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
# Create your views here.
from django.utils import timezone

from check_app.models import Result, ConfirmationPart
from olymp.settings import HAS_STARTED
from test_app.forms import RadioForm, CheckboxForm, InputForm, TextAreaForm
from test_app.gen.generator import generator
from test_app.gen.process_post import process_post
from test_app.gen.testgetter import get_test_form, get_millis
from test_app.models import AnswerTmp, Question, UsedTimes, Test, Subject, LastUsed, Submission, UserAnswer
from test_app.sturcts.log_struct import LogStruct
from userman.forms import ConfirmationForm
from userman.models import Contestant, School


def check_if_finished(request):
    test = Test.objects.first()
    assert isinstance(test, Test)
    # print timezone.now().microsecond, test.end_date, test.end_date < datetime.now()
    # return False
    print test.end_date < timezone.now()
    # On the olymp
    return test.end_date < timezone.now()


@login_required()
def confirm_1st(request):
    contestant = Contestant.objects.filter(user=request.user)
    if len(contestant) != 0:
        contestant = contestant.first()
        assert isinstance(contestant, Contestant)

        if not HAS_STARTED:
            return render(request, 'test_app/not_started.html')
        if contestant.started:
            return HttpResponseRedirect(reverse('test-app:home'))
        else:
            return render(request, 'test_app/base.html')


@login_required()
def home(request):
    print "Here"
    if request.user.is_staff:
        return HttpResponseRedirect(reverse('check:questions_list'))
    if not request.user.is_active:
        return render(request, 'test_app/activation_required.html')
    if not HAS_STARTED:
        return render(request, 'test_app/not_started.html')
    # if not HAS_STARTED:
    #     return HttpResponseRedirect(reverse('test-app:not_started'))
    contestant = Contestant.objects.filter(user=request.user)
    if len(contestant) != 0:
        contestant = contestant.first()
        assert isinstance(contestant, Contestant)

        if not contestant.started:
            return HttpResponseRedirect(reverse('test-app:confirm_1st'))
        if contestant.finished:
            return HttpResponseRedirect(reverse('test-app:process'))
        if contestant.started:
            return HttpResponseRedirect(reverse('test-app:process'))
        if check_if_finished(request):
            return render(request, 'test_app/olympf.html')
    # return HttpResponseRedirect(reverse('test-app:process'))
    return render(request, 'test_app/base.html')


@login_required()
def process(request, question_number=-1):
    print "Here 111"
    if not request.user.is_active:
        return render(request, 'test_app/activation_required.html')
    if request.user.is_staff:
        return HttpResponseRedirect(reverse('check:home'))
    if not HAS_STARTED:
        return render(request, 'test_app/not_started.html')
    try:
        contestant = Contestant.objects.get(user=request.user)
        print "Found"
    except Contestant.DoesNotExist:
        print "Here"
        return render(request, 'test_app/base.html')
    if check_if_finished(request) or contestant.finished:
        print "Heresadasdas"
        return render(request, 'test_app/olympf.html')
    question_number = int(question_number)

    if contestant.finished:
        return HttpResponseRedirect(reverse('test-app:finally-finished'))
    context = {}
    if request.POST:
        process_post(request, contestant, question_number)
        question_number += 1

    if not contestant.started:
        contestant.started = True
        contestant.save()
        generator(contestant)

    if question_number == -1:
        question_number = 1

    context = get_test_form(contestant, question_number)
    # print context['time']
    if context['finished']:
        return HttpResponseRedirect(reverse('test-app:finished'))
    if context['timeout']:
        return HttpResponseRedirect(reverse('test-app:timeout'))

    return render(request, 'test_app/test.html', context)


@login_required()
def finished(request):
    if not HAS_STARTED:
        return render(request, 'test_app/not_started.html')
    contestant = Contestant.objects.get(user=request.user)
    return render(request, 'test_app/finished.html', {'time': get_millis(contestant)})


@login_required()
def finally_finished(request):
    if not HAS_STARTED:
        return render(request, 'test_app/not_started.html')
    try:
        contestant = Contestant.objects.get(user=request.user)
        contestant.finished = True
        contestant.save()
    except Contestant.DoesNotExist:
        pass
    return HttpResponseRedirect(reverse('logoutt'))


@login_required()
def update_db(request):
    sum1 = 0
    sum2 = 0
    useds = []
    lus = []
    if request.user.is_superuser:
        # used_times init
        schools = School.objects.all()
        subjects = Subject.objects.all()
        questions = Question.objects.all()
        test = Test.objects.first()
        questions2 = {}
        for subject in subjects:
            questions2[subject.name] = Question.objects.filter(subject=subject).values('question_number').distinct()
        for school in schools:
            for question in questions:
                sum1 += 1
                used = UsedTimes()
                used.school = school
                used.subject = question.subject
                used.question = question
                used.used_times = 0
                used.test = test
                useds.append(used)
        for school in schools:
            for subject in subjects:
                for question in questions2[subject.name]:
                    sum2 += 1
                    lu = LastUsed()
                    lu.subject = subject
                    lu.school = school
                    lu.question_number = question['question_number']
                    lu.test = test
                    lu.last_used = 0
        #             lus.append(lu)
        # LastUsed.objects.bulk_create(lus)
        # UsedTimes.objects.bulk_create(useds)
    return HttpResponse('UT = ' + str(sum1) + " LU " + str(sum2))


@login_required()
def timeout(request):
    return render(request, 'test_app/timeout.html')


@login_required()
def test_html(request):
    return render(request, 'test_app/activation_required.html')


@login_required()
def results(request):
    global contestant, submission
    try:
        contestant = Contestant.objects.get(user=request.user)
    except Contestant.DoesNotExist:
        print "No such contestant"
    try:
        submission = Submission.objects.get(contestant=contestant)
    except:
        print "No submission defined with this contestant"
    res = []
    uanswers = UserAnswer.objects.filter(submission=submission)
    sum = 0
    print len(uanswers)
    for answer in uanswers:
        question = answer.question
        txt = ""
        cans = ""
        if question.type == 'R':
            ans = answer.answer.all()
            if ans.count() > 0:
                txt = ans[0].text
                cans = question.answer_set.all().get(is_correct=True).text
                if ans[0].is_correct:
                    sum += 1
        elif question.type == 'I':
            answer_text = answer.answer_text
            correct_answer_text = question.answer_set.all()[0].text
            cans = correct_answer_text
            txt = answer_text
            if answer_text is not None and correct_answer_text is not None:
                answer_text = answer_text.lower()
                answer_text = answer_text.replace(',', '.').strip()
                correct_answer_text = correct_answer_text.lower()
                correct_answer_text = correct_answer_text.replace(',', '.').strip()
                if correct_answer_text == answer_text:
                    sum += 1
        elif question.type == 'A':
            txt = answer.answer_text
            try:
                cans = question.answer_set.all().get(is_correct=True).text
            except:
                print "Oop"
            if answer.is_correct:
                sum += 1
        res.append(LogStruct(question=question.text, uans=txt, cans=cans))

    context = {'score': sum, 'res': res, 'passed': sum >= 15, 'uid': contestant.result_set.all()[0].id}
    return render(request, 'test_app/review.html', context)


def final_results(request):
    context = {}
    res = Result.objects.all()
    res = res[:114]
    ind = 1
    res2 = []
    for i in res:
        assert isinstance(i, Result)
        tmp = {
            'user': i.contestant.user.last_name + " " + i.contestant.user.first_name + " " + i.contestant.fathers_name,
            'school': i.contestant.school.school,
            'district': i.contestant.school.rayon,
            'score': i.score,
            'place': ind
        }
        if i.score >= 19:
            res2.append(tmp)
            ind += 1
    context['res'] = res2

    return render(request, 'test_app/results.html', context)


@login_required()
def confirm_part(request):
    global cont
    passed = False
    try:
        result = Result.objects.get(contestant__user=request.user)
        passed = result.score >= 34
    except Result.DoesNotExist:
        print "OOps"
    if not passed:
        return HttpResponseRedirect(reverse('test-app:final'))
    form = ConfirmationForm()
    context = {'form': form}
    if request.POST:
        form = ConfirmationForm(request.POST)
        if form.is_valid():
            tmp = ConfirmationPart()
            try:
                cont = Contestant.objects.get(user=request.user)
            except:
                print "oopss"
            tmp.contestant = cont

olymp/test_app/templates/test_app/activation_required.html
{% extends 'test_app/base.html' %}

{% block title %}
 Необходимо активировать аккаунт!
{% endblock %}

{% block content %}
 <div class="col-md-12">
                  <div class="box">
                <div class="box-header with-border">
                  <h3 class="box-title">Активируйте ваш email.</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <center>
                  <div class="btn-group" role="group" aria-label="...">
                      Пожалуйста, проверьте вашу почту и активируйте ваш пользователь, перейдя по ссылке из соообщения на почте!
                  </center>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

olymp/test_app/templates/test_app/base.html
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}
        Index
    {% endblock %}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="{% static 'userman/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
  <script src="{% static 'userman/plugins/jQuery/jQuery-2.1.4.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'userman/css/AdminLTE.min.css' %}">
  <script type="text/javascript" src="{% static 'userman/js/timer.js' %}"></script>
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link rel="stylesheet" href="{% static 'userman/css/skin-yellow.min.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  <style type="text/css">
    .time {
      color: white;
      padding-left: 20px;
    }
    .timeButton {
      margin-left: 10px;
      margin-top: 10px;
    }
    </style>
  </head>
{#onmousedown="return false;" onclick="return true;"#}
  <body class="hold-transition skin-yellow  sidebar-mini" >

    <div class="wrapper">

      <!-- Main Header -->
      <header class="main-header">

        <!-- Logo -->
        <a href="{% url 'test-app:home' %}" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>МЕЛ</b></span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>МЕЛ</b>ОЛИМПИАДА</span>
        </a>

        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          </a>
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->

              <!-- User Account Menu -->
              {% block navbar %}

{##}
{#                <li class="dropdown user user-menu">#}
{#                <!-- Menu Toggle Button -->#}
{#                <a href="{% url 'test-app:finished' %}">#}
{#                  <!-- The user image in the navbar-->#}
{##}
{#                  <!-- hidden-xs hides the username on small devices so only the image appears. -->#}
{#                  <span class="hidden-xs">Завершить олимпиаду</span>#}
{#                </a>#}
{#              </li>#}
                  {% endblock %}
              <li>
                <a href="{% url 'logoutt' %}">Выйти</a>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
          <section class="sidebar">
              {% block sidebar %}

                        <h3 class="time">Олимпиада еще не началась или вы закончили ее писать</h3>

              {% endblock %}
          </section>
        <!-- sidebar: style can be found in sidebar.less -->
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            {% block secheader %}


          <h1>

            <small></small>
          </h1>
          <ol class="breadcrumb">
          </ol>
            {% endblock %}
        </section>

        <!-- Main content -->
        <section class="content">
{% block content %}
        <div class="col-md-12">
              <div class="box">
                <div class="box-header with-border">
                  <h3 class="box-title">Инструкция по тестирующей системе</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <div class="btn-group">
                      <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown"><i class="fa fa-wrench"></i></button>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                      </ul>
                    </div>
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                <div>
                    <ol>
                      <li>Написать олимпиаду можно только один раз.</li>
                      <li>Длительность олимпиады – 1.5 часа</li>
                      <li>Результаты будут известны 18 мая в 12.00</li>
                        <li>Во время олимпиады можно вернуться к уже отвеченному вопросу и исправить его (на панели с цифрами).</li>
                        <li>Количество исправлений никак не влияет на результат. Засчитывается последний выбранный вариант ответа.</li>
                        <li>Ответ пишите строго. (Без лишних пробелов, переводов строк)</li>
                        <li>Успехов!</li>
                    </ol>
                </div>



                </div>
            </div>
        </div>


        <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md-4">
            <br><a href="{% url 'test-app:process' %}" class="btn btn-block btn-success btn-lg">Начать тест</a>
          </div>
        </div>





{% endblock %}
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

      <!-- Main Footer -->
      <footer class="main-footer">
        <!-- To the right -->
        <div class="pull-right hidden-xs">
{#          Anything you want#}
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; 2018 <a href="#">МЕЛ 2018</a>.</strong> Все права защищены.
          По всем вопросам обращайтесь: <a href="Mailto:inbox@mel-olymp.ru">inbox@mel-olymp.ru</a>
      </footer>

        <!-- Control Sidebar -->
      <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
      <div class="control-sidebar-bg"></div>
    </div><!-- ./wrapper -->

    <!-- REQUIRED JS SCRIPTS -->

    <!-- jQuery 2.1.4 -->

    <!-- Bootstrap 3.3.5 -->
    <script src="{% static 'userman/js/bootstrap.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'userman/js/app.min.js' %}"></script>

  </body>
</html>

olymp/test_app/templates/test_app/confirm.html
<html>
<head>
    <meta http-equiv="refresh" content="3;url={% url 'test-app:final' %}">
    <meta charset="UTF-8">
    <title>Ваше сообщение отправлено</title>
</head>
<body>
<P>Мы сохранили ваш результат! Спасибо! Вы будете перенаправлены автоматически на страницу с списком прошедших</P>
</body>
</html>

olymp/test_app/templates/test_app/not_started.html
{% extends 'test_app/base.html' %}
{% block title %}
    Олимпиада не началась
{% endblock %}

{% block content %}
    <p>Здравствуйте!Олимпиада закончилась.Результаты будут опубликованы 22 апреля 2018</p>
{% endblock %}

olymp/test_app/templates/test_app/olympf.html
{% extends 'test_app/base.html' %}

{% block title %}
    Олимпиада завершена
{% endblock %}

{% block content %}
    <p>Олимпиада завершена. Спасибо за участие. Результаты будут известны 1 мая в 12.00 в ваших личных кабинетах</p>
{% endblock %}

olymp/test_app/templates/test_app/results.html
{% extends 'test_app/base.html' %}

{% block title %}
    Список приглашенных
{% endblock %}

{% block secheader %}
{#    {% if passed %}#}
{#            <div class="col-md-12">#}
{#        <div class="box">#}
{#                    <div class="box-header with-border">#}
{#                        <h3 class="box-title text-red">Внимание!</h3>#}
{#                    </div><!-- /.box-header -->#}
{#                    <div class="box-body">#}
{#                        <div>#}
{#                            <p>Поздравляем! Вы прошли!</p>#}
{#                            <p> <span class="text-green text-center text-bold">Вы прошли!</span> Подтвердите свое участие, перейдя по данной <a href="{% url 'test-app:confirm' %}">ссылке</a></p>#}
{#                            <P>Подробная информация по очному этапу будет 20 мая.</P>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#    {% endif %}#}
        <p>Подтвердите участие по данному <a href="https://docs.google.com/forms/d/e/1FAIpQLScHsCQA-UmfEYfAjzcA5_g-XjNaa6oqYcs2IMKKolCjobOFHQ/viewform">адресу</a></P>

{#    <p>Подтвердите участие по данному <a href="{% url 'test-app:confirm' %}https://goo.gl/forms/CvT8J9z1cqetG4gI3">адресу</a></P>#}
{% endblock %}

{% block content %}
    <div class="col-md-12">
        <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Список приглашенных на 2(очный) тур олимпиады</h3>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                    <table class="table table-responsive">
                    <tr><th>#</th><th>ФИО</th><th>Район</th><th>Школа</th><th>Балл</th></tr>
                        {% for elem in res %}
                            <tr>
                                <td>{{ elem.place }}</td>
                                <td>{{elem.user }}</td>
                                <td>{{elem.district }}</td>
                                <td>{{elem.school }}</td>
                                <td>{{elem.score }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                    </div>
                </div>
            </div>

{% endblock %}

olymp/test_app/templates/test_app/review.html
{% extends 'test_app/base.html' %}

{% block title %}
    Результат тестирования.
{% endblock %}

{% block secheader %}

            <div class="col-md-12">
        <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title text-red">Внимание!</h3>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        <div>
                            <p>Сертификат участника заочного этапа вы можете скачать <a href="{% url 'check:gen' uid %}">здесь</a></p>
                            {% if passed %}
                            <p>Поздравляем! Вы прошли!</p>
                            <p> <span class="text-green text-center text-bold">Вы прошли!</span> Подтвердите свое участие, перейдя по данной <a href="{% url 'test-app:confirm' %}">ссылке</a></p>
                            <P>Подробная информация по очному этапу будет 8 мая.</P>
                                <p>Ваш сертификат участника очного этапа вы можете скачать <a href="{% url 'check:gen2' uid %}">здесь</a></p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

{% endblock %}

{% block content %}
    <h1>Ваши результаты:</h1>
    {% for elem in res %}
    <div class="col-md-12">
        <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">{{ elem.question|safe }}</h3>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        <div>
                            <P class="text-center">Ответ участника</P>
                            <p class="text-center"><blockquote class="text-center">{{ elem.uans|safe }}</blockquote>
                            <p class="text-center text-green">Правильный ответ</p>
                            <p><blockquote class="text-center text-green">{{ elem.cans|safe }}</blockquote></p>
                        </div>
                    </div>
                </div>
            </div>
{% endfor %}
            <div class="row text-center">
                <p>Итого: {{ score }}</p>
            </div>
{% endblock %}

olymp/test_app/templates/test_app/timeout.html
{% extends 'test_app/base.html' %}

{% block title %}
Онлайн тур написан
{% endblock %}

{% block content %}
    <p>Спасибо за участие ваше время вышло. Олимпиада написана. Ваши результаты сохранены. Результаты будут известны 1 мая в 12.00 на нашем сайте.</p>
    <p><a href="{% url 'test-app:finally-finished' %}" class="btn btn-block btn-success btn-lg">Завершить</a></p>
{% endblock %}