olymp/api/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('api.views',
                       # Examples:
                       # url(r'^$', 'tosterproject.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       url(r'^get_schools/', 'get_schools', name='get_schools'),
                       url(r'^$', 'home', name='home'),
                       url(r'^get_districts/', 'get_districts', name='get_districts'),
                       url(r'^csv/', 'upload_data', name='upload-data')

                       )

olymp/check_app/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('check_app.views',
                       # Examples:
                       # url(r'^$', 'tosterproject.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),
                       url(r"^$", 'index', name='home'),
                       url(r"^process/(?P<id>[0-9]+)/$", 'user_check', name='process'),
                       url(r"^results/$", 'results', name='results'),
                       url(r'^list/$', 'list', name='list'),
                       url(r'^pdf/(?P<uid>[0-9]+)/$', 'get_pdf', name='pdf'),
                       url(r'^stats/$', 'stats', name='stats'),
                       url(r'^will/$', 'get_list_of_participants', name='parts'),
                       url(r'^gen/(?P<uid>[0-9]+)/$', 'gen_pdf', name='gen'),
                       url(r'^gen2/(?P<uid>[0-9]+)/$', 'gen_pdf_onsite', name='gen2'),
                       url(r'^pdf2/(?P<uid>[0-9]+)/$', 'get_pdf_nosite', name='pdf2'),
                       url(r'^questions/(?P<subject_id>[0-9]+)$', 'questions_list',
                           name='questions'),
                       url(r'^questions/', 'questions_list', name='questions_list'),
                       url(r'^partstats/', 'statistics_participants', name='partstats')
                       # url(r'^login/$', LoginView.as_view(), name='login'),
                       # url(r'^logout/$', 'log_out', name='logout'),
                       # url(r'^class/(?P<class_id>\d+)/$', 'class_journal', name='class_journal'),
                       # url(r'^test/$', 'raiting2', name='raiting2'),
                       # url(r'^class/(?P<class_id>\d+)/master$', 'class_journal', name='my_class'),
                       # url(r'^student/(?P<student_id>\d+)/$', 'student_profile', name='student'),
                       # url(r'^raiting/$', 'raiting', name='raiting'),
                       # url(r'^inc/$', 'increase', name='inc')
                       # url(r'^event/(?P<event_id>\d+)/edit/$', 'event_edit', name='event_edit')
                       )

olymp/olymp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import password_reset
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from olymp import settings
from userman.views import LoginView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', LoginView.as_view(), name='loginn'),
    url(r'^$', 'userman.views.index', name='main'),
    url(r'^register/', 'userman.views.register', name='register'),
    url(r'^logout/', 'userman.views.log_out', name='logoutt'),
    url(r'^accounts/registration/$',
        password_reset,
        {'html_email_template_name':
             'registration/password_reset_email_html.html', },
        name='registration',
        ),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^data/upload/', 'userman.data_manager.backup.upload', name='upload'),
    url(r"^api/", include('api.urls'), name="api"),
    url(r'^confirm/(?P<activation_key>\w+)/', 'userman.views.register_confirm', name='register_confirm'),
    url(r'^register_success/', 'userman.views.register_success', name='register_success'),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^contact/', 'userman.views.contact', name='contact'),
    url(r'^test/', include('test_app.urls', namespace='test-app')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}
        ),
    url(r'^check/', include('check_app.urls', namespace='check')),
    url(r'^program/', 'userman.views.program', name='program'),

]

urlpatterns += staticfiles_urlpatterns()

olymp/check_app/models.py
# coding=utf-8
from __future__ import unicode_literals
from django.db import models
# Create your models here.
from userman.models import Contestant


class Result(models.Model):
    contestant = models.ForeignKey(Contestant, verbose_name=u'Участник', unique=True)
    score = models.IntegerField(verbose_name=u'Балл')

    class Meta:
        ordering = ['-score']


CHOICES_CONFIRM = (('M', u'Мама'), ('F', 'Папа'))


class ConfirmationPart(models.Model):
    contestant = models.OneToOneField(Contestant, verbose_name=u'Участник')
    will_come = models.BooleanField(verbose_name=u'Приедет?')
    who = models.CharField(choices=CHOICES_CONFIRM, max_length=1)
    phone_number = models.CharField(max_length=20, verbose_name=u'Нормер телефона')

olymp/check_app/forms.py
# coding=utf-8
from django import forms

from test_app.models import UserAnswer

CHOICES = ((None, u"Не знаю"),
           (True, u"Верно"),
           (False, u"Неверно"),)


class CheckboxForm(forms.ModelForm):
    question = None
    answer_text = None
    answer = None

    def __init__(self, question, answer_text, answer, *args, **kwargs):
        super(CheckboxForm, self).__init__(*args, **kwargs)
        self.question = question
        self.answer_text = answer_text
        self.answer = answer

    class Meta:
        model = UserAnswer
        fields = ('is_correct',)
        widgets = {
             'is_correct': forms.RadioSelect(choices=CHOICES),
        }

olymp/check_app/views.py
# coding=utf-8
from datetime import timedelta
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db.models import Count, Max
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
# Create your views here.
from django.utils import timezone

from check_app.data_structures.form_keeper import FormKeeper
from check_app.data_structures.get_form import get_form
from check_app.data_structures.struct_res import Student
from check_app.forms import CheckboxForm
from check_app.models import Result, ConfirmationPart
from olymp import settings
from test_app.models import Submission, Subject, UserAnswer
from userman.models import Contestant, Rayon, School
import logging



class Submissions:
    def __init__(self, subm_id, user, css, teacher, is_linked):
        self.id = subm_id
        self.user = user
        self.css = css
        self.teacher = teacher
        self.is_linked = is_linked


@login_required()
def index(request):
    if not request.user.is_staff:
        return HttpResponseRedirect(reverse('test-app:process'))
    countall = Submission.objects.all().count()
    submissions = Submission.objects.filter(is_checked=False).order_by('date_started')
    res = []
    checked_count = Submission.objects.filter(checked_by=request.user).count()
    context = {'all': countall, 'checked': countall - submissions.count(), 'count': checked_count}
    submissions = submissions[:25]
    dt = timedelta(hours=0, minutes=5, seconds=0)
    is_linked = True

    for submission in submissions:
        user = submission.contestant.user.last_name + " " + submission.contestant.user.first_name + \
               " " + submission.contestant.fathers_name
        css = "fa fa-question-circle"
        teacher = ''
        if (submission.start_checking is not None and timezone.now() < submission.start_checking + dt) and (
                    request.user != submission.checked_by):
            teacher = submission.checked_by
            css = 'glyphicon glyphicon-lock'
        if submission.is_checked:
            css = 'fa fa-check-circle'
        res.append(Submissions(subm_id=submission.id, user=user, css=css, teacher=teacher, is_linked=is_linked))
    context['submissions'] = res
    return render(request, 'check_app/index.html', context=context)


@login_required()
def user_check(request, id=-1):
    if not request.user.is_staff:
        return HttpResponseRedirect(reverse('test-app:process'))
    global submission
    id = int(id)

    try:
        submission = Submission.objects.get(pk=id)
        dt = timedelta(hours=0, minutes=5, seconds=0)
        if submission.start_checking is None or timezone.now() >= submission.start_checking + dt:
            submission.start_checking = timezone.now()
            submission.checked_by = request.user
            submission.save()
        elif submission.checked_by != request.user:
            return HttpResponseRedirect(reverse('check:home'))
    except Submission.DoesNotExist:
        print 'No such submission'

    try:
        subject = Subject.objects.get(name__icontains=u'Естествознание')
    except Subject.DoesNotExist:
        print 'No such subject'

    answers = UserAnswer.objects.filter(submission=submission, question__subject=subject)
    forms = []
    for answer in answers:
        atext = answer.answer_text
        qtext = answer.question.text
        ans = answer.question.answer_set.all()
        if ans.count() > 0:
            ans = ans[0]
        form = CheckboxForm(qtext, atext, ans, instance=answer, prefix=str(answer.id))
        forms.append(form)

    if request.POST:
        forms = []
        valid = True
        for answer in answers:
            atext = answer.answer_text
            qtext = answer.question.text
            ans = answer.question.answer_set.all()
            if ans.count > 0:
                ans = ans[0]
            form = CheckboxForm(qtext, atext, ans, request.POST, instance=answer, prefix=str(answer.id))
            forms.append(form)
            if form.is_valid():
                obj = form.save()
            else:
                valid = False
        if valid:
            submission.is_checked = True
            submission.checked_by = request.user
            submission.save()

            return HttpResponseRedirect(reverse('check:home'))
    return render(request, 'check_app/user_check_page.html', {'forms': forms})


def list(request):
    countall = Submission.objects.all().count()
    context = {'all': countall, 'checked': countall - Submission.objects.filter(is_checked=False).count()}
    lst = []

    obj = Submission.objects.all().values('checked_by').exclude(checked_by=None).annotate(
        total=Count('checked_by')).order_by('-checked_by')
    for elem in obj:
        tmp = {'count': elem['total'], 'user': User.objects.get(pk=elem['checked_by']).username}
        lst.append(tmp)
    print tmp
    context['list'] = lst
    return render(request, 'check_app/list.html', context)


def results(request):
    context = {}
    submissions = Submission.objects.all()
    res = []
    res2 = []
    k = 0
    for submission in submissions:
        sum = 0
        k += 1
        print k
        uanswers = UserAnswer.objects.filter(submission=submission)
        for answer in uanswers:
            question = answer.question
            if question.type == 'R':
                ans = answer.answer.all()
                if ans.count() > 0:
                    if ans[0].is_correct:
                        sum += 1
            elif question.type == 'I':
                answer_text = answer.answer_text
                correct_answer_text = question.answer_set.all()[0].text
                if answer_text is not None and correct_answer_text is not None:
                    answer_text = answer_text.lower()
                    answer_text = answer_text.replace(',', '.').strip()
                    correct_answer_text = correct_answer_text.lower()
                    correct_answer_text = correct_answer_text.replace(',', '.').strip()
                    if correct_answer_text == answer_text:
                        sum += 1
            elif question.type == 'A':
                if answer.is_correct:
                    sum += 1
        if len(uanswers) > 30:
            sum /= 3
            sum = int(sum)
        tmp = Result()
        tmp.contestant = submission.contestant
        tmp.score = sum
        res2.append(tmp)
        name = submission.contestant.user.last_name + " " + submission.contestant.user.first_name + \
               " " + submission.contestant.fathers_name
        res.append(Student(name, sum))
    Result.objects.bulk_create(res2)
    res.sort(key=lambda x: x.score, reverse=True)
    pl = 1
    for i in res:
        i.place = pl
        pl += 1
    context['students'] = res

    return render(request, 'check_app/raiting.html', context)


def stats(request):
    context = {}
    submissions = Submission.objects.all()
    res = []
    subjects = Subject.objects.all()
    stat_res = {}
    time_res = {}
    question_count = {}

    for i in subjects:
        stat_res[i] = 0
        time_res[i] = timedelta(hours=0, minutes=0, seconds=0)
        tmp = i.question_set.all().aggregate(Max('question_number'))
        question_count[i] = tmp['question_number__max']
    for submission in submissions:
        sum = 0
        uanswers = UserAnswer.objects.filter(submission=submission)
        for answer in uanswers:

            question = answer.question

            if question.type == 'R':
                ans = answer.answer.all()
                if ans.count() > 0:
                    if ans[0].is_correct:
                        sum += 1
            elif question.type == 'I':
                answer_text = answer.answer_text
                correct_answer_text = question.answer_set.all()[0].text
                if answer_text is not None and correct_answer_text is not None:
                    answer_text = answer_text.lower()
                    answer_text = answer_text.replace(',', '.').strip()
                    correct_answer_text = correct_answer_text.lower()
                    correct_answer_text = correct_answer_text.replace(',', '.').strip()
                    if correct_answer_text == answer_text:
                        sum += 1
            elif question.type == 'A':
                if answer.is_correct:
                    sum += 1
        name = submission.contestant.user.last_name + " " + submission.contestant.user.first_name + \
               " " + submission.contestant.fathers_name
        res.append(Student(submission, sum))
    res.sort(key=lambda x: x.score, reverse=True)
    pl = 1
    res = res[:162]
    for i in res:
        i.place = pl
        pl += 1

    for subm in res:
        assert isinstance(subm.name, Submission)
        uanswers = UserAnswer.objects.filter(submission=subm.name)
        for answer in uanswers:
            question = answer.question
            try:
                time_res[question.subject] += answer.end_time - answer.start_time
            except TypeError:
                pass
            if question.type == 'R':
                ans = answer.answer.all()
                if ans.count() > 0:
                    if ans[0].is_correct:
                        stat_res[question.subject] += 1

            elif question.type == 'I':
                answer_text = answer.answer_text
                correct_answer_text = question.answer_set.all()[0].text
                if answer_text is not None and correct_answer_text is not None:
                    answer_text = answer_text.lower()
                    answer_text = answer_text.replace(',', '.').strip()
                    correct_answer_text = correct_answer_text.lower()
                    correct_answer_text = correct_answer_text.replace(',', '.').strip()

olymp/check_app/templates/check_app/index.html
{% extends 'test_app/base.html' %}

{% block title %}
    Проверка заданий
{% endblock %}

{% block secheader %}
          <h1>
            Проверка заданий
          </h1>
          <ol class="breadcrumb">
            <li class="active"><i class="fa fa-dashboard"></i>Список пользователей</li>
          </ol>
{% endblock %}
{% block content %}
    <div class="row">
    <div class="box-body">
        <h3>Проверено: {{ checked }} / {{ all }}</h3>
        <h4>Вы проверили: {{ count }}</h4>
          <table class="table table-bordered table-hover">
              <caption>Список написавших тест</caption>
              <tr>
                  <th>Участник</th>
                  <th>Проверяется?</th>
                  <th>Пользователь</th>
              </tr>
              {% for submission in submissions  %}
                <tr>

                    <td>{% if submission.is_linked %}
                        <a href="{% url 'check:process' submission.id %}">{{ submission.user }}</a>
                        {% else %}
                        <span>{{ submission.user }}</span>
                    {% endif %} </td>
                    <td><i class="{{ submission.css }}"></i></td>
                    <td>{{ submission.teacher }}</td>
                </tr>
              {% endfor %}
          </table>
    </div>
    </div>
{% endblock %}

olymp/check_app/templates/check_app/list.html
{% extends 'test_app/base.html' %}

{% block content %}
    <div class="row">
    <div class="box-body">
        <h3>Проверено: {{ checked }} / {{ all }}</h3>
        <table class="table">
            <tr><th>Username</th><th>Count</th></tr>
            {% for elem in list %}
                <tr><td>{{ elem.user }}</td>
                <td>{{ elem.count }}</td></tr>
            {% endfor %}


        </table>

    </div>
    </div>
{% endblock %}

olymp/check_app/templates/check_app/main.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'userman/css/main.css'  %}">
    
	<title>MEL</title>

</head>
<body>
    <div class="maincard">
        <div class="top"></div>
        <img class="header" src="{% static 'userman/img/header.png' %}"/>
        <h1 class="textheader">Настоящим подтверждается, что</h1>
        <h2 class="username">{{ name }},</h2>
{#        <h3 class="texthead">ученик(ца) 10 класса</h3>#}
        <h3 class="texthead0"> {% if gender %}
            учащийся
            {% else %}
            учащаяся
        {% endif %}
            {{ school }}</h3>
        <h4 class="texthead0">принял(а) участие в Республиканской олимпиаде<br>
МЕЛ (математика, естествознание, логика) в 1 туре.<br>
(количество набранных баллов {{ score }} из 50)</h4>
        <img class="footer" src="{% static 'userman/img/auth.png' %}"/>
        <div class="date">22 мая 2016г.</div>
    </div>
</body>
</html>

olymp/check_app/templates/check_app/onsite.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'userman/css/main.css'  %}">

	<title>MEL</title>

</head>
<body>
    <div class="maincard">
        <div class="top"></div>
        <img class="header" src="{% static 'userman/img/header.png' %}"/>
        <h1 class="textheader">Настоящим подтверждается, что</h1>
        <h2 class="username">{{ name }},</h2>
{#        <h3 class="texthead">ученик(ца) 10 класса</h3>#}
        <h3 class="texthead0"> {% if gender %}
            учащийся
            {% else %}
            учащаяся
        {% endif %}
            {{ school }}</h3>
        <h4 class="texthead0">принял(а) участие в Республиканской олимпиаде<br>
МЕЛ (математика, естествознание, логика) в 2(очном) туре.<br></h4>
        <img class="footer" src="{% static 'userman/img/auth.png' %}"/>
        <div class="date">22 мая 2016г.</div>
    </div>
</body>
</html>

olymp/check_app/templates/check_app/participants.html
{% extends 'test_app/base.html' %}

{% block title %}
Список участников
{% endblock %}


{% block content %}
    <div class="row">
    <div class="box-body">
        <table class="table">
            <tr><th>ФИО</th><th>Пол</th><th>Класс</th><th>Район</th><th>Школа</th><th>Номер телефона</th><th>Балл</th><th>Приедет?</th><th>email</th></tr>
            {% for student in students %}

                <tr>
                <td>{{ student.name }}</td>
                    <td>{{ student.gender }}</td>
                    <td>{{ student.class }}</td>
                    <td>{{ student.district }}</td>
                <td>{{ student.school }}</td>
                <td>{{ student.phone }}</td>
                <td>{{ student.score }}</td>
                <td>{{ student.will }}</td>
                <td>{{ student.email }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    </div>
{% endblock %}

olymp/check_app/templates/check_app/questions.html
{% extends 'test_app/base.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block sidebar %}

    <!-- Menu Toggle Button -->
    {% for subject in subjects %}
        <li class="dropdown user user-menu">
            <a href="{% url 'check:questions' subject.id %}">{{ subject.name }}
                <!-- The user image in the navbar-->

                <!-- hidden-xs hides the username on small devices so only the image appears. -->

            </a>
        </li>
    {% endfor %}



{% endblock %}

{% block content %}
    {% for fk in forms %}



        <div class="col-md-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Задание № {{ fk.question_number }}</h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <div class="btn-group">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown"><i
                                    class="fa fa-wrench"></i></button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                        </div>
                    </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div>
                        <p>
                            {{ fk.question_text|safe }}
                        </p>
                    </div>


                </div><!-- ./box-body -->

            </div>
        </div>
        {% ifequal fk.form.type 'R' %}



            {% csrf_token %}
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    {% for field in fk.form.choices %}
                        <center><label class="radio-inline">
                            {{ field.tag }} {{ field.choice_label|safe }}

                        </label></center>
                    {% endfor %}

                </div>
            </div>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                </div>
            </div>


            {#        <div class="row">#}
            {#          <div class="col-md-4"></div>#}
            {#          <div class="col-md-4">#}
            {#          </div>#}

            {#               </div>#}
        {% endifequal %}

        {% ifequal fk.form.type 'C' %}
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    {% for field in fk.form.choices %}
                        <label class="checkbox">
                            {{ field.tag }} {{ field.choice_label|safe }}
                        </label>
                        {#                    <p>{{ field }}</p>#}
                    {% endfor %}
                </div>

            </div>

            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                </div>
            </div>
        {% endifequal %}

        {% ifequal fk.form.type 'A' %}
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    {{ fk.form.answer }}
                </div>

                <div class="row">
                    <div class="col-md-4"></div>
                    <div class="col-md-4">
                    </div>
                </div>
            </div>
        {% endifequal %}

        {% ifequal form.type 'I' %}
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    {{ fk.form.answer }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4"></div>
            </div>
            </div>


        {% endifequal %}
    {% endfor %}
{% endblock %}

olymp/check_app/templates/check_app/raiting.html
{% extends 'test_app/base.html' %}

{% block title %}
    Результат олимпиады
{% endblock %}


{% block content %}
    <div class="row">
    <div class="box-body">
        <table class="table">
            <tr><th>#</th><th>ФИО</th><th>Балл</th></tr>
            {% for student in students %}

                <tr>
                <td>{{ student.place }}</td>
                    <td>{{ student.name }}</td>
                <td>{{ student.score }}</td></tr>
            {% endfor %}
        </table>
    </div>
    </div>
{% endblock %}

olymp/check_app/templates/check_app/statistcs_pariticipants.html
{% extends 'test_app/base.html' %}
{% block title %}
    Статистика олимпиады
{% endblock %}

{% block content %}
    <div class="row">
    <div class="box-body">
        <table class="table">
            <tr><th>#</th><th>ФИО</th><th>Балл</th></tr>
            {% for student in students %}

                <tr>
                <td>{{ student.place }}</td>
                    <td>{{ student.name }}</td>
                <td>{{ student.score }}</td></tr>
            {% endfor %}
        </table>
    </div>
    </div>
{% endblock %}

olymp/check_app/templates/check_app/user_check_page.html
{% extends 'test_app/base.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block secheader %}
    {{ contestant }}
{% endblock %}

{% block content %}
     <form method="post">
 {% csrf_token %}
         {% for form in forms %}
    <div class="col-md-12">
        <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">{{ form.question|safe }}</h3>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        <div>
                            <P class="text-center">Ответ участника</P>
                            <p class="text-center"><blockquote>{{ form.answer_text }}</blockquote>
                            <p class="text-center text-green">Правильный ответ</p>
                            <p><blockquote class="text-center text-green">{{ form.answer }}</blockquote></p>

                            {{ form.as_p }}
                        </div>


                    </div>
                </div>
                <!-- Your Page Content Here -->
            </div>
{% endfor %}
            <div class="row text-center">
                <input type="submit" value="Сохранить">
            </div>
 </form>
{% endblock %}